server:
  port: ${SERVER_PORT:8103}
spring:
  application:
    name: budget-pacing-service
  redis:
    host: ${REDIS_HOST:redis}
    port: ${REDIS_PORT:6379}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URLS:http://eureka-server-1:8761/eureka/,http://eureka-server-2:8761/eureka/}
  instance:
    prefer-ip-address: true
