#!/usr/bin/env bash
#
# Materialises Deployment/.env from OCI Vault, immediately before `docker compose up`.
#
# WHY THIS EXISTS
#   Deployment/.env held six live credentials and was tracked in git and pushed, from 2026-07-05
#   until 2026-08-28. Rotating them fixes the exposure; this stops it recurring, by making the VM
#   the only place a plaintext secret ever exists and making that copy transient.
#
# WHY INSTANCE PRINCIPALS
#   The VM authenticates by BEING that VM. There is no API key, no ~/.oci/config, no private key on
#   disk. Every other approach needs a credential to fetch the credentials, which is the problem
#   restated one level down.
#
# PREREQUISITES (one-time, in the OCI console)
#   1. A Vault with a master encryption key.
#   2. A secret per name in SECRET_NAMES below.
#   3. A dynamic group matching this instance:
#        ANY {instance.id = 'ocid1.instance.oc1.<region>.<this-vm>'}
#   4. A policy in the vault's compartment:
#        Allow dynamic-group <name> to read secret-family in compartment <compartment>
#      `secret-family` matters: scoping to `secrets` alone lists them but cannot read the value,
#      which surfaces as a confusing 404 rather than a permission error.
#
# USAGE
#   export OCI_VAULT_ID=ocid1.vault.oc1...
#   ./fetch_secrets_from_vault.sh          # writes ../.env (chmod 600)
#
set -euo pipefail

VAULT_ID="${OCI_VAULT_ID:-}"
ENV_FILE="$(cd "$(dirname "$0")/.." && pwd)/.env"

# Every secret the compose file interpolates today.
#
# IDENTITY_HMAC_SECRET signs the gateway-minted identity headers (X-User-Id, X-User-Roles, ...) that
# every downstream service trusts in place of re-validating the JWT. The gateway mints the signature;
# the services verify it by recomputing. Both sides must hold an identical value or every
# authenticated request 403s, so this is deployed to all 19 containers at once -- which is safe here
# because a compose deploy restarts them together and nothing is serving during it.
# AUCTION_TOKEN_SECRET is here, unlike IDENTITY_HMAC_SECRET, because the compose wiring landed with
# it: all 19 Java service containers name it in their `environment:` block (18 modules; EurekaServer
# runs twice). ONDCIntegrationService and ReviewsService are commented out of compose, so there is
# nothing to wire for them.
#
# BiddingEngine encrypts the auction clearing price into the tracking pixel URL with it, and
# UserTrackingService decrypts it to bill the advertiser -- those two must hold an identical value or
# every impression billing event stops. The other 17 only instantiate the bean (AuctionTokenService
# is an unconditional @Service in CommonLibrary, which all 20 apps component-scan); they never call
# it, but under the 'prod' profile its constructor throws when this is unset, so they all need it.
SECRET_NAMES=(
  AUCTION_TOKEN_SECRET
  IDENTITY_HMAC_SECRET
  POSTGRES_PASS
  CONFIG_PASSWORD
  EUREKA_PASSWORD
  R2_ACCESS_KEY_ID
  R2_SECRET_ACCESS_KEY
  OLA_MAPS_API_KEY
)

if [[ -z "$VAULT_ID" ]]; then
  echo "FATAL: OCI_VAULT_ID is not set." >&2
  exit 1
fi
[[ -d "$HOME/bin" ]] && export PATH="$HOME/bin:$PATH"
command -v oci >/dev/null 2>&1 || { echo "FATAL: the oci CLI is not installed." >&2; exit 1; }

echo "Fetching ${#SECRET_NAMES[@]} secrets from OCI Vault using the instance principal..."

TMP_ENV="$(mktemp)"
# Never leave a half-written .env behind: a missing value would start a service with a blank
# password, which fails later and further away than it should.
trap 'rm -f "$TMP_ENV"' EXIT

DEFAULTS_FILE="$(cd "$(dirname "$0")/.." && pwd)/.env.defaults"
if [[ ! -f "$DEFAULTS_FILE" ]]; then
  echo "FATAL: $DEFAULTS_FILE is missing. It carries every non-secret key; without it the" >&2
  echo "       generated .env would be incomplete (empty POSTGRES_USER, clobbered" >&2
  echo "       ALLOWED_ORIGINS) and services would start misconfigured." >&2
  exit 1
fi

{
  echo "# Generated by fetch_secrets_from_vault.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "# Do NOT commit. Do NOT edit by hand:"
  echo "#   secrets      -> change in OCI Vault and re-run"
  echo "#   non-secrets  -> change Deployment/.env.defaults and re-run"
  echo
  cat "$DEFAULTS_FILE"
  echo
  echo "# --- from OCI Vault ---"
} > "$TMP_ENV"

for name in "${SECRET_NAMES[@]}"; do
  if ! encoded="$(oci secrets secret-bundle get-secret-bundle-by-name \
        --secret-name "$name" \
        --vault-id "$VAULT_ID" \
        --auth instance_principal \
        --query 'data."secret-bundle-content".content' \
        --raw-output 2>/dev/null)"; then
    echo "FATAL: could not read '$name' from the vault. Check the secret exists and that the" >&2
    echo "       dynamic-group policy grants 'read secret-family' in its compartment." >&2
    exit 1
  fi

  value="$(printf '%s' "$encoded" | base64 -d)"
  if [[ -z "$value" ]]; then
    echo "FATAL: '$name' is present but empty. Refusing to write a blank credential." >&2
    exit 1
  fi

  printf '%s=%s\n' "$name" "$value" >> "$TMP_ENV"
  echo "  ok  $name (${#value} chars)"
done

# Every key the compose file interpolates must end up set. A missing one is not a warning: an empty
# POSTGRES_USER stops Postgres starting, an empty ALLOWED_ORIGINS breaks CORS in a way that looks
# like a frontend bug.
missing=()
while read -r required; do
  [[ -z "$required" ]] && continue
  grep -q "^${required}=" "$TMP_ENV" || missing+=("$required")
done < <(grep -oE '\$\{[A-Z0-9_]+' "$(dirname "$ENV_FILE")/docker-compose.yml" \
         | tr -d '${' | sort -u \
         | grep -vE '_TAG$|^REGISTRY$')
# _TAG and REGISTRY are deployment state, not configuration: deploy.sh injects them from
# Deployment/.versions at deploy time so a container's image is decided by a recorded tag rather
# than by whatever someone last typed into .env. Requiring them here would force the tag of a
# running container into a hand-edited file, which is the opposite of what .versions is for.
if (( ${#missing[@]} > 0 )); then
  echo "FATAL: docker-compose.yml interpolates these, and the generated .env does not set them:" >&2
  printf '       %s\n' "${missing[@]}" >&2
  echo "       Add non-secrets to .env.defaults, or the name to SECRET_NAMES if it is a credential." >&2
  exit 1
fi

install -m 600 "$TMP_ENV" "$ENV_FILE"
echo "Wrote $ENV_FILE (mode 600, $(wc -l < "$ENV_FILE") lines). Values were not printed."
