-- Generated by generate_scenario_data.py. Additive; preserves existing fixture state.
BEGIN;
INSERT INTO customers (id, phone_number) VALUES ('8f3bd8bb-a7d6-57ae-ae28-5a9137b47de9', '8000000501') ON CONFLICT DO NOTHING;
INSERT INTO customer_addresses (id, customer_id, label, address_line1, city, state, zip_code, latitude, longitude, is_default, city_id) VALUES ('93696bd2-409b-5fe7-91ec-cef24e666694', '8f3bd8bb-a7d6-57ae-ae28-5a9137b47de9', 'Home', 'E2E Scenario Home', 'Bangalore', 'Karnataka', '560001', 12.99, 77.67, TRUE, 'BLR') ON CONFLICT DO NOTHING;
INSERT INTO customers (id, phone_number) VALUES ('db45c5f8-71b5-57ff-94fb-4af8f99930c7', '8000000502') ON CONFLICT DO NOTHING;
INSERT INTO customers (id, phone_number) VALUES ('6f9325bd-c469-5cd8-af6d-3e4601f61df6', '8000000503') ON CONFLICT DO NOTHING;
INSERT INTO customer_addresses (id, customer_id, label, address_line1, city, state, zip_code, latitude, longitude, is_default, city_id) VALUES ('ecbd5fbc-90d6-53ff-9fad-94b9b1040bf6', '6f9325bd-c469-5cd8-af6d-3e4601f61df6', 'Home', 'E2E Scenario Home', 'Bangalore', 'Karnataka', '560001', 12.99, 77.67, TRUE, 'BLR') ON CONFLICT DO NOTHING;
INSERT INTO customers (id, phone_number) VALUES ('676217dd-582e-5714-9079-22773837fefe', '8000000504') ON CONFLICT DO NOTHING;
INSERT INTO customer_addresses (id, customer_id, label, address_line1, city, state, zip_code, latitude, longitude, is_default, city_id) VALUES ('82b81042-72fc-5a00-99cf-f5e22d65bff3', '676217dd-582e-5714-9079-22773837fefe', 'Home', 'E2E Scenario Home', 'Hyderabad', 'Telangana', '500001', 17.385, 78.4867, TRUE, 'HYD') ON CONFLICT DO NOTHING;
COMMIT;
