-- Generated by generate_scenario_data.py. Additive; preserves existing fixture state.
BEGIN;
DO $$ BEGIN IF EXISTS (SELECT FROM users WHERE phone_number='8000000501' AND id<>'8f3bd8bb-a7d6-57ae-ae28-5a9137b47de9') THEN RAISE EXCEPTION 'Scenario phone collision: 8000000501'; END IF; END $$;
INSERT INTO users (id, phone_number, name, email, is_active) VALUES ('8f3bd8bb-a7d6-57ae-ae28-5a9137b47de9', '8000000501', NULL, NULL, TRUE) ON CONFLICT DO NOTHING;
INSERT INTO user_roles (id, user_id, service_name, role_name) VALUES ('581cdab3-644f-5d7a-992b-144621e4a196', '8f3bd8bb-a7d6-57ae-ae28-5a9137b47de9', 'CustomerApplication', 'CUSTOMER') ON CONFLICT DO NOTHING;
DO $$ BEGIN IF EXISTS (SELECT FROM users WHERE phone_number='8000000502' AND id<>'db45c5f8-71b5-57ff-94fb-4af8f99930c7') THEN RAISE EXCEPTION 'Scenario phone collision: 8000000502'; END IF; END $$;
INSERT INTO users (id, phone_number, name, email, is_active) VALUES ('db45c5f8-71b5-57ff-94fb-4af8f99930c7', '8000000502', 'E2E no-address', 'scenario-8000000502@example.com', TRUE) ON CONFLICT DO NOTHING;
INSERT INTO user_roles (id, user_id, service_name, role_name) VALUES ('f4e9a6c6-ce3f-54eb-9c18-a17bc86adc5e', 'db45c5f8-71b5-57ff-94fb-4af8f99930c7', 'CustomerApplication', 'CUSTOMER') ON CONFLICT DO NOTHING;
DO $$ BEGIN IF EXISTS (SELECT FROM users WHERE phone_number='8000000503' AND id<>'6f9325bd-c469-5cd8-af6d-3e4601f61df6') THEN RAISE EXCEPTION 'Scenario phone collision: 8000000503'; END IF; END $$;
INSERT INTO users (id, phone_number, name, email, is_active) VALUES ('6f9325bd-c469-5cd8-af6d-3e4601f61df6', '8000000503', 'E2E suspended', 'scenario-8000000503@example.com', FALSE) ON CONFLICT DO NOTHING;
INSERT INTO user_roles (id, user_id, service_name, role_name) VALUES ('59fb2120-87bb-52c1-a168-2c2e430f0723', '6f9325bd-c469-5cd8-af6d-3e4601f61df6', 'CustomerApplication', 'CUSTOMER') ON CONFLICT DO NOTHING;
DO $$ BEGIN IF EXISTS (SELECT FROM users WHERE phone_number='8000000504' AND id<>'676217dd-582e-5714-9079-22773837fefe') THEN RAISE EXCEPTION 'Scenario phone collision: 8000000504'; END IF; END $$;
INSERT INTO users (id, phone_number, name, email, is_active) VALUES ('676217dd-582e-5714-9079-22773837fefe', '8000000504', 'E2E second-city', 'scenario-8000000504@example.com', TRUE) ON CONFLICT DO NOTHING;
INSERT INTO user_roles (id, user_id, service_name, role_name) VALUES ('a8395816-495a-5314-82a5-afede63ce944', '676217dd-582e-5714-9079-22773837fefe', 'CustomerApplication', 'CUSTOMER') ON CONFLICT DO NOTHING;
DO $$ BEGIN IF EXISTS (SELECT FROM users WHERE phone_number='7000000031' AND id<>'a00bb0f6-85a1-56ba-82c2-b50da35f72af') THEN RAISE EXCEPTION 'Scenario phone collision: 7000000031'; END IF; END $$;
INSERT INTO users (id, phone_number, name, email, is_active) VALUES ('a00bb0f6-85a1-56ba-82c2-b50da35f72af', '7000000031', 'E2E pending-kyc', 'scenario-7000000031@example.com', TRUE) ON CONFLICT DO NOTHING;
INSERT INTO user_roles (id, user_id, service_name, role_name) VALUES ('86ce967f-6e74-5ea4-b060-fb6d72b77e34', 'a00bb0f6-85a1-56ba-82c2-b50da35f72af', 'DeliveryExecutiveApplication', 'DELIVERY') ON CONFLICT DO NOTHING;
DO $$ BEGIN IF EXISTS (SELECT FROM users WHERE phone_number='7000000032' AND id<>'3ab875e7-62c9-5f7e-94da-a7fbac93b89b') THEN RAISE EXCEPTION 'Scenario phone collision: 7000000032'; END IF; END $$;
INSERT INTO users (id, phone_number, name, email, is_active) VALUES ('3ab875e7-62c9-5f7e-94da-a7fbac93b89b', '7000000032', 'E2E rejected-kyc', 'scenario-7000000032@example.com', TRUE) ON CONFLICT DO NOTHING;
INSERT INTO user_roles (id, user_id, service_name, role_name) VALUES ('59438d53-7479-5c10-8553-b6cec96c8800', '3ab875e7-62c9-5f7e-94da-a7fbac93b89b', 'DeliveryExecutiveApplication', 'DELIVERY') ON CONFLICT DO NOTHING;
DO $$ BEGIN IF EXISTS (SELECT FROM users WHERE phone_number='7000000033' AND id<>'b704753b-22f1-5133-8917-b47dcaee1796') THEN RAISE EXCEPTION 'Scenario phone collision: 7000000033'; END IF; END $$;
INSERT INTO users (id, phone_number, name, email, is_active) VALUES ('b704753b-22f1-5133-8917-b47dcaee1796', '7000000033', 'E2E approved-offline', 'scenario-7000000033@example.com', TRUE) ON CONFLICT DO NOTHING;
INSERT INTO user_roles (id, user_id, service_name, role_name) VALUES ('d0471fce-9dde-5d88-bb9e-f4d9dc25b0d4', 'b704753b-22f1-5133-8917-b47dcaee1796', 'DeliveryExecutiveApplication', 'DELIVERY') ON CONFLICT DO NOTHING;
DO $$ BEGIN IF EXISTS (SELECT FROM users WHERE phone_number='7000000034' AND id<>'9c517c1f-576e-5287-974c-342afcf28fb5') THEN RAISE EXCEPTION 'Scenario phone collision: 7000000034'; END IF; END $$;
INSERT INTO users (id, phone_number, name, email, is_active) VALUES ('9c517c1f-576e-5287-974c-342afcf28fb5', '7000000034', 'E2E inactive-rider', 'scenario-7000000034@example.com', TRUE) ON CONFLICT DO NOTHING;
INSERT INTO user_roles (id, user_id, service_name, role_name) VALUES ('119a977c-d737-5b35-8510-31fb539f55bc', '9c517c1f-576e-5287-974c-342afcf28fb5', 'DeliveryExecutiveApplication', 'DELIVERY') ON CONFLICT DO NOTHING;
DO $$ BEGIN IF EXISTS (SELECT FROM users WHERE phone_number='9000000011' AND id<>'d5e4cc0d-315d-5f3f-b923-6535a028d07f') THEN RAISE EXCEPTION 'Scenario phone collision: 9000000011'; END IF; END $$;
INSERT INTO users (id, phone_number, name, email, is_active) VALUES ('d5e4cc0d-315d-5f3f-b923-6535a028d07f', '9000000011', 'E2E no-brand', 'scenario-9000000011@example.com', TRUE) ON CONFLICT DO NOTHING;
INSERT INTO user_roles (id, user_id, service_name, role_name) VALUES ('1ffa83a7-ad6a-55cc-9471-bfb26769e206', 'd5e4cc0d-315d-5f3f-b923-6535a028d07f', 'RestaurantApplication', 'RESTAURANT') ON CONFLICT DO NOTHING;
DO $$ BEGIN IF EXISTS (SELECT FROM users WHERE phone_number='9000000012' AND id<>'1de2fa20-8064-5c2b-8060-d0b9bb0bf0ba') THEN RAISE EXCEPTION 'Scenario phone collision: 9000000012'; END IF; END $$;
INSERT INTO users (id, phone_number, name, email, is_active) VALUES ('1de2fa20-8064-5c2b-8060-d0b9bb0bf0ba', '9000000012', 'E2E pending-brand', 'scenario-9000000012@example.com', TRUE) ON CONFLICT DO NOTHING;
INSERT INTO user_roles (id, user_id, service_name, role_name) VALUES ('b1859bc8-c461-5146-be2a-7c447abf3fc0', '1de2fa20-8064-5c2b-8060-d0b9bb0bf0ba', 'RestaurantApplication', 'RESTAURANT') ON CONFLICT DO NOTHING;
DO $$ BEGIN IF EXISTS (SELECT FROM users WHERE phone_number='9000000013' AND id<>'7228bb44-08e1-5f24-af6b-c86fc50962f7') THEN RAISE EXCEPTION 'Scenario phone collision: 9000000013'; END IF; END $$;
INSERT INTO users (id, phone_number, name, email, is_active) VALUES ('7228bb44-08e1-5f24-af6b-c86fc50962f7', '9000000013', 'E2E rejected-brand', 'scenario-9000000013@example.com', TRUE) ON CONFLICT DO NOTHING;
INSERT INTO user_roles (id, user_id, service_name, role_name) VALUES ('4d214eb8-d0df-5d1a-96eb-94b86051dcda', '7228bb44-08e1-5f24-af6b-c86fc50962f7', 'RestaurantApplication', 'RESTAURANT') ON CONFLICT DO NOTHING;
DO $$ BEGIN IF EXISTS (SELECT FROM users WHERE phone_number='9000000014' AND id<>'61957f14-78ad-5fba-9500-aa5a0fef59d8') THEN RAISE EXCEPTION 'Scenario phone collision: 9000000014'; END IF; END $$;
INSERT INTO users (id, phone_number, name, email, is_active) VALUES ('61957f14-78ad-5fba-9500-aa5a0fef59d8', '9000000014', 'E2E inactive-outlet-and-unavailable-dish', 'scenario-9000000014@example.com', TRUE) ON CONFLICT DO NOTHING;
INSERT INTO user_roles (id, user_id, service_name, role_name) VALUES ('3ac4fcfe-d3e9-51b7-9e93-8bef57ddf4bd', '61957f14-78ad-5fba-9500-aa5a0fef59d8', 'RestaurantApplication', 'RESTAURANT') ON CONFLICT DO NOTHING;
DO $$ BEGIN
IF EXISTS (SELECT FROM users u WHERE u.phone_number='1000000001' AND NOT EXISTS
    (SELECT FROM user_roles r WHERE r.user_id=u.id AND r.role_name='ADMIN' AND lower(r.service_name) IN ('admin','adminapplication'))) THEN
    RAISE EXCEPTION 'Admin phone collision: 1000000001';
END IF;
END $$;
INSERT INTO users (id, phone_number, name, email, is_active) VALUES ('4e1f984b-ff9f-5af8-82ff-a5923096f1f1', '1000000001', 'E2E Admin 1', 'e2e-admin-1@example.com', TRUE) ON CONFLICT DO NOTHING;
INSERT INTO user_roles (id,user_id,service_name,role_name) SELECT '8aa76040-e8bf-5e6f-9167-1f4e093b3fd2',id,'ADMIN','ADMIN' FROM users WHERE phone_number='1000000001' ON CONFLICT DO NOTHING;
DO $$ BEGIN
IF EXISTS (SELECT FROM users u WHERE u.phone_number='1000000002' AND NOT EXISTS
    (SELECT FROM user_roles r WHERE r.user_id=u.id AND r.role_name='ADMIN' AND lower(r.service_name) IN ('admin','adminapplication'))) THEN
    RAISE EXCEPTION 'Admin phone collision: 1000000002';
END IF;
END $$;
INSERT INTO users (id, phone_number, name, email, is_active) VALUES ('2e41ccb3-0bb9-5e4a-8190-340171a0131d', '1000000002', 'E2E Admin 2', 'e2e-admin-2@example.com', TRUE) ON CONFLICT DO NOTHING;
INSERT INTO user_roles (id,user_id,service_name,role_name) SELECT '4c3866ce-031a-5c08-90cf-4f3eedbb003d',id,'ADMIN','ADMIN' FROM users WHERE phone_number='1000000002' ON CONFLICT DO NOTHING;
COMMIT;
